export { lerp } from './src/lerp'
export { unlerp } from './src/unlerp'
export { clamp } from './src/clamp'
export { sequence } from './src/sequence'
export { pseudoRandom } from './src/pseudoRandom'
